import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CanvasContainer } from "@/app/@canvas/components/CanvasContainer";
import { Leva } from "leva";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  canvas,
}: Readonly<{
  children: React.ReactNode;
  canvas: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CanvasContainer>{canvas}</CanvasContainer>
        {children}
      </body>
    </html>
  );
}
