/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Bonsai_Tree_1: THREE.Mesh;
    Bonsai_Tree_2: THREE.Mesh;
    Bonsai_Tree_3: THREE.Mesh;
    Bonsai_Tree_4: THREE.Mesh;
    Bonsai_Tree_5: THREE.Mesh;
    Bonsai_Tree_6: THREE.Mesh;
    Bonsai_Tree_7: THREE.Mesh;
    Planter: THREE.Mesh;
    Rocks: THREE.Mesh;
    Soil: THREE.Mesh;
  };
  materials: {
    Bark: THREE.MeshStandardMaterial;
    Leaf_1: THREE.MeshStandardMaterial;
    Leaf_2: THREE.MeshStandardMaterial;
    Leaf_3: THREE.MeshStandardMaterial;
    Leaf_4: THREE.MeshStandardMaterial;
    Leaf_5: THREE.MeshStandardMaterial;
    Leaf_6: THREE.MeshStandardMaterial;
    Planter: THREE.MeshStandardMaterial;
    Rock: THREE.MeshStandardMaterial;
    ["Soil.002"]: THREE.MeshStandardMaterial;
  };
};

export function Bonsai(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/bonsai.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[-0.022, 0.081, 0.588]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bonsai_Tree_1.geometry}
          material={materials.Bark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bonsai_Tree_2.geometry}
          material={materials.Leaf_1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bonsai_Tree_3.geometry}
          material={materials.Leaf_2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bonsai_Tree_4.geometry}
          material={materials.Leaf_3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bonsai_Tree_5.geometry}
          material={materials.Leaf_4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bonsai_Tree_6.geometry}
          material={materials.Leaf_5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bonsai_Tree_7.geometry}
          material={materials.Leaf_6}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Planter.geometry}
        material={materials.Planter}
        position={[0, 0.038, 0.027]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rocks.geometry}
        material={materials.Rock}
        position={[0.031, 0.015, 0.071]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Soil.geometry}
        material={materials["Soil.002"]}
        position={[0, 0.038, 0.066]}
      />
    </group>
  );
}

useGLTF.preload("/models/bonsai.glb");
