/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { SmallMonstera } from "./SmallMonstera";
import { SmallPlant } from "./SmallPlant";
import { OvergrownPlant } from "./OvergrownPlant";
import { Succulent } from "./Succulent";
import { Books } from "./Books";
import { DecorativeStone } from "./DecorativeStone";
import { WhaleWickerBasket } from "./WhaleWickerBasket";
import { GlobeDecor } from "./GlobeDecor";
import { Bonsai } from "./Bonsai";
import { Vases } from "./Vases";

type GLTFResult = GLTF & {
  nodes: {
    Asymmetric_bookshelf: THREE.Mesh;
  };
  materials: {
    ["Desk wood.001"]: THREE.MeshPhysicalMaterial;
  };
};

export function Bookshelf(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/bookshelf-opt.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <SmallMonstera position={[0.2, 0, 1.02]} scale={0.8} />
      <WhaleWickerBasket
        scale={0.4}
        position={[0.35, 0, -0.215]}
        rotation={[0, 0, Math.PI - 0.35]}
      />
      <DecorativeStone position={[-0.37, 0, 0.185]} />
      <Succulent position={[0.3, 0, 0.6]} scale={1.2} />
      <Vases position={[0.05, 0, 0.2]} />
      <Books position={[-0.35, -0.03, -0.2]} rotation={[0, 0, 0]} />
      <GlobeDecor position={[-0.305, 0.05, -0.6]} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Asymmetric_bookshelf.geometry}
        material={materials["Desk wood.001"]}
      />
    </group>
  );
}
