/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cube009: THREE.Mesh;
    Cube009_1: THREE.Mesh;
  };
  materials: {
    book_encyclopedia_set_01_cover: THREE.MeshStandardMaterial;
    book_encyclopedia_set_01_paper: THREE.MeshStandardMaterial;
  };
};

export function Books(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/books-opt.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[0.256, -0.019, 0.119]} scale={0.276}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009.geometry}
          material={materials.book_encyclopedia_set_01_cover}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_1.geometry}
          material={materials.book_encyclopedia_set_01_paper}
        />
      </group>
    </group>
  );
}
