/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useEffect, useRef, useState } from "react";
import { useCursor, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { Shelf } from "./Shelf";

type GLTFResult = GLTF & {
  nodes: {
    Plane005_1: THREE.Mesh;
    Plane007_1: THREE.Mesh;
    Plane008_1: THREE.Mesh;
    Wood_8001_1: THREE.Mesh;
    Wood_9001_1: THREE.Mesh;
    Wood_8005_1: THREE.Mesh;
    Wood_9004_1: THREE.Mesh;
    Plane011_1: THREE.Mesh;
  };
  materials: {
    Leg_1001: THREE.MeshStandardMaterial;
    Chair_1001: THREE.MeshStandardMaterial;
    ["Cushion _1001"]: THREE.MeshStandardMaterial;
  };
};

export function Chair(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/chair-model.glb") as GLTFResult;
  const [hovered, set] = useState(false);
  useCursor(hovered, "pointer");
  return (
    <group
      {...props}
      dispose={null}
      onPointerOver={() => set(true)}
      onPointerOut={() => set(false)}
    >
      <group
        scale={0.00011}
        rotation={new THREE.Euler(1.57, 0, 0)}
        position={[0, 0.1, 0]}
      >
        <mesh
          castShadow
          geometry={nodes.Plane005_1.geometry}
          material={materials.Leg_1001}
          position={[1802.484, 4419.811, 549.859]}
          rotation={[-1.671, 1.393, 0]}
          scale={167.213}
        />
        <mesh
          castShadow
          geometry={nodes.Plane007_1.geometry}
          material={materials.Leg_1001}
          position={[-302.963, 3253.031, 3866.427]}
          rotation={[-0.067, 0, 0]}
          scale={123.542}
        />
        <mesh
          castShadow
          geometry={nodes.Plane008_1.geometry}
          material={materials.Leg_1001}
          position={[-302.963, 3131.192, 283.316]}
          rotation={[-0.067, 0, 0]}
          scale={123.542}
        />
        <mesh
          castShadow
          geometry={nodes.Wood_8001_1.geometry}
          material={materials.Chair_1001}
          position={[61.425, 4566.988, 2700.24]}
        />
        <mesh
          castShadow
          geometry={nodes.Wood_9001_1.geometry}
          material={materials.Chair_1001}
          position={[-12.014, 6447.972, 85.483]}
          scale={1.019}
        />
        <mesh
          castShadow
          geometry={nodes.Wood_8005_1.geometry}
          material={materials["Cushion _1001"]}
          position={[45.863, 4560.354, 2663.64]}
          scale={0.961}
        />
        <mesh
          castShadow
          geometry={nodes.Wood_9004_1.geometry}
          material={materials["Cushion _1001"]}
          position={[-12.014, 6447.972, 214.542]}
          scale={0.986}
        />
        <mesh
          castShadow
          geometry={nodes.Plane011_1.geometry}
          material={materials.Leg_1001}
          position={[1802.484, 4419.811, 549.859]}
          rotation={[-1.671, 1.393, 0]}
          scale={167.213}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/chair-model.glb");
