/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Stone: THREE.Mesh;
    Wood: THREE.Mesh;
  };
  materials: {
    Stone: THREE.MeshStandardMaterial;
    ["Wood.001"]: THREE.MeshStandardMaterial;
  };
};

export function DecorativeStone(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/decorative-stone-opt.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stone.geometry}
        material={materials.Stone}
        position={[0, 0, 0.13]}
        scale={0.083}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wood.geometry}
        material={materials["Wood.001"]}
        position={[0, 0, 0.04]}
        scale={0.082}
      />
    </group>
  );
}

useGLTF.preload("/models/decorative-stone-opt.glb");
