/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    MainFloor: THREE.Mesh;
  };
  materials: {
    Floor: THREE.MeshStandardMaterial;
  };
};

export function Floor(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/floor.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MainFloor.geometry}
        material={materials.Floor}
        scale={[9.468, 3.824, 6.383]}
        renderOrder={2}
      />
    </group>
  );
}

useGLTF.preload("/models/floor.glb");
