/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Hanging_shelf: THREE.Mesh;
  };
  materials: {
    ["Desk wood.002"]: THREE.MeshPhysicalMaterial;
  };
};

export function HangingShelf(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/hanging-shelf-opt.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Hanging_shelf.geometry}
        material={materials["Desk wood.002"]}
        position={[-0.001, -0.09, 0.285]}
        rotation={[1.571, -0.006, 0.006]}
        scale={0.35}
      />
    </group>
  );
}

useGLTF.preload("/models/hanging-shelf-opt.glb");
