/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cylinder001: THREE.Mesh;
    Cube005: THREE.Mesh;
    Plane003: THREE.Mesh;
    Cube007: THREE.Mesh;
    Plane013: THREE.Mesh;
    Cube009: THREE.Mesh;
    Cube010: THREE.Mesh;
    Plane001: THREE.Mesh;
    Cube011: THREE.Mesh;
    Plane005: THREE.Mesh;
    Cube012: THREE.Mesh;
    Plane012: THREE.Mesh;
    Cube013: THREE.Mesh;
    Plane007: THREE.Mesh;
    Plane009: THREE.Mesh;
    Bolt: THREE.Mesh;
  };
  materials: {
    ["vase-cross"]: THREE.MeshStandardMaterial;
    stem: THREE.MeshStandardMaterial;
    leaf: THREE.MeshStandardMaterial;
    ["dirt.001"]: THREE.MeshStandardMaterial;
    ["wood.001"]: THREE.MeshStandardMaterial;
    ["Material.006"]: THREE.MeshStandardMaterial;
  };
};

export function IndoorShelfPlant(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/indoor-shelf-plant.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials["vase-cross"]}
        position={[0, 0, 0.14]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005.geometry}
          material={materials.stem}
          position={[-0.002, -0.022, 0.014]}
          rotation={[0, -0.12, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane003.geometry}
            material={materials.leaf}
            position={[-0.113, 0.008, 0.245]}
            rotation={[0.032, 0.828, 0.622]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007.geometry}
          material={materials.stem}
          position={[0.004, -0.02, 0.075]}
          rotation={[-0.217, -0.227, -1.378]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane013.geometry}
            material={materials.leaf}
            position={[-0.018, -0.013, 0.081]}
            rotation={[-0.657, 0.815, 1.592]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009.geometry}
          material={materials["dirt.001"]}
          position={[0, 0, 0.081]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010.geometry}
          material={materials.stem}
          position={[0.01, -0.018, 0.03]}
          rotation={[0, 0, -1.98]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane001.geometry}
            material={materials.leaf}
            position={[-0.083, -0.007, 0.165]}
            rotation={[-0.059, 0.539, 0.747]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube011.geometry}
          material={materials.stem}
          position={[0.009, -0.025, 0.037]}
          rotation={[0, 0, 2.266]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane005.geometry}
            material={materials.leaf}
            position={[-0.058, -0.035, 0.119]}
            rotation={[-0.102, 0.521, 0.72]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube012.geometry}
          material={materials.stem}
          position={[-0.009, -0.031, 0.025]}
          rotation={[0.423, -0.269, 0.791]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane012.geometry}
            material={materials.leaf}
            position={[-0.016, -0.019, 0.089]}
            rotation={[-0.657, 0.815, 1.592]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013.geometry}
          material={materials.stem}
          position={[0.007, -0.016, 0.062]}
          rotation={[0, 0, -1.847]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane007.geometry}
            material={materials.leaf}
            position={[-0.056, -0.032, 0.117]}
            rotation={[-0.604, 0.511, 1.672]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane009.geometry}
          material={materials["wood.001"]}
          position={[0, 0, -0.087]}
          rotation={[0, 0, Math.PI / 4]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Bolt.geometry}
            material={materials["Material.006"]}
          />
        </mesh>
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/indoor-shelf-plant.glb");
