/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useLoader } from "@react-three/fiber";
import { imageKitLoader } from "@/app/utils/loader";

type GLTFResult = GLTF & {
  nodes: {
    Painting_MR_FOX001: THREE.Mesh;
    Painting_MR_FOX001_1: THREE.Mesh;
    Painting_MR_FOX001_2: THREE.Mesh;
  };
  materials: {
    ["moldura.001"]: THREE.MeshStandardMaterial;
    ["Pintura.001"]: THREE.MeshStandardMaterial;
    ["vidro.001"]: THREE.MeshPhysicalMaterial;
  };
};

export function PaintingFox(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/painting-fox.glb"
  ) as GLTFResult;

  const [colorMap, normalMap, roughnessMap, metalnessMap] = useTexture(
    [
      "/textures/VeneerWhiteOakRandomMatched001-4K/VeneerWhiteOakRandomMatched001_COL_4K_METALNESS.png",
      "/textures/VeneerWhiteOakRandomMatched001-4K/VeneerWhiteOakRandomMatched001_NRM_4K_METALNESS.png",
      "/textures/VeneerWhiteOakRandomMatched001-4K/VeneerWhiteOakRandomMatched001_ROUGHNESS_4K_METALNESS.png",
      "/textures/VeneerWhiteOakRandomMatched001-4K/VeneerWhiteOakRandomMatched001_METALNESS_4K_METALNESS.png",
    ].map((src) => imageKitLoader({ src }))
  ).map((texture) => {
    texture.flipY = false;
    return texture;
  });

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Painting_MR_FOX001.geometry}
      >
        <meshStandardMaterial
          map={colorMap}
          normalMap={normalMap}
          metalnessMap={metalnessMap}
          roughnessMap={roughnessMap}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Painting_MR_FOX001_1.geometry}
        material={materials["Pintura.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Painting_MR_FOX001_2.geometry}
        material={materials["vidro.001"]}
      />
    </group>
  );
}
