/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useLoader } from "@react-three/fiber";
import { imageKitLoader } from "@/app/utils/loader";

type GLTFResult = GLTF & {
  nodes: {
    Painting_Number_5001_1: THREE.Mesh;
    Painting_Number_5001_2: THREE.Mesh;
    Painting_Number_5001_3: THREE.Mesh;
  };
  materials: {
    ["Frame.001"]: THREE.MeshStandardMaterial;
    ["Painting.001"]: THREE.MeshStandardMaterial;
    ["Glass.001"]: THREE.MeshStandardMaterial;
  };
};

export function PaintingYellow(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/painting-yellow.glb"
  ) as GLTFResult;

  const [colorMap, normalMap, roughnessMap, metalnessMap] = useTexture(
    [
      "/textures/VeneerWhiteOakRandomMatched001-4K/VeneerWhiteOakRandomMatched001_COL_4K_METALNESS.png",
      "/textures/VeneerWhiteOakRandomMatched001-4K/VeneerWhiteOakRandomMatched001_NRM_4K_METALNESS.png",
      "/textures/VeneerWhiteOakRandomMatched001-4K/VeneerWhiteOakRandomMatched001_ROUGHNESS_4K_METALNESS.png",
      "/textures/VeneerWhiteOakRandomMatched001-4K/VeneerWhiteOakRandomMatched001_METALNESS_4K_METALNESS.png",
    ].map((src) => imageKitLoader({ src }))
  ).map((texture) => {
    texture.flipY = false;
    return texture;
  });

  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Painting_Number_5001_1.geometry}
        >
          <meshStandardMaterial
            map={colorMap}
            normalMap={normalMap}
            metalnessMap={metalnessMap}
            roughnessMap={roughnessMap}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Painting_Number_5001_2.geometry}
          material={materials["Painting.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Painting_Number_5001_3.geometry}
          material={materials["Glass.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/painting-yellow.glb");
