/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useFBX, useGLTF, useTexture } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useLoader } from "@react-three/fiber";
import { imageKitLoader } from "@/app/utils/loader";

type GLTFResult = GLTF & {
  nodes: {
    PlantPalm001001: THREE.Mesh;
    PlantPalmVase001001: THREE.Mesh;
  };
  materials: {
    PlantPalm001_2K: THREE.MeshStandardMaterial;
    PlantPalmVase001_2K: THREE.MeshStandardMaterial;
  };
};

export function Plant(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF(
    "/models/PlantPalm001/PlantPalm001-opt.glb"
  ) as GLTFResult;

  const [plantColorMap, plantNormalMap, plantRoughnessMap, plantMetalnessMap] =
    useTexture(
      [
        "/models/PlantPalm001/PlantPalm001_COL_4K_METALNESS.jpg",
        "/models/PlantPalm001/PlantPalm001_NRM_4K_METALNESS.jpg",
        "/models/PlantPalm001/PlantPalm001_ROUGHNESS_4K_METALNESS.jpg",
        "/models/PlantPalm001/PlantPalm001_METALNESS_4K_METALNESS.jpg",
      ].map((src) => imageKitLoader({ src }))
    ).map((texture) => {
      return texture;
    });
  const [vaseColorMap, vaseNormalMap, vaseRoughnessMap, vaseMetalnessMap] =
    useTexture(
      [
        "/models/PlantPalm001/PlantPalmVase001_COL_4K_METALNESS.jpg",
        "/models/PlantPalm001/PlantPalmVase001_NRM_2K_METALNESS.png",
        "/models/PlantPalm001/PlantPalmVase001_ROUGHNESS_4K_METALNESS.jpg",
        "/models/PlantPalm001/PlantPalmVase001_METALNESS_4K_METALNESS.jpg",
      ].map((src) => imageKitLoader({ src }))
    ).map((texture) => {
      texture.flipY = false;
      return texture;
    });

  return (
    <group {...props}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PlantPalm001001.geometry}
        position={[-0.659, -0.085, -0.114]}
        scale={0.499}
      >
        <meshStandardMaterial
          map={plantColorMap}
          normalMap={plantNormalMap}
          roughnessMap={plantRoughnessMap}
          metalnessMap={plantMetalnessMap}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PlantPalmVase001001.geometry}
        position={[-0.613, -0.142, -0.716]}
        scale={0.14}
      >
        <meshStandardMaterial
          map={vaseColorMap}
          normalMap={vaseNormalMap}
          roughnessMap={vaseRoughnessMap}
          metalnessMap={vaseMetalnessMap}
        />
      </mesh>
    </group>
  );
}
