/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useFBX, useGLTF, useTexture } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useLoader } from "@react-three/fiber";
import { imageKitLoader } from "@/app/utils/loader";

type GLTFResult = GLTF & {
  nodes: {
    PlantBanjoFig001001: THREE.Mesh;
    PlantBanjoFigVase001001: THREE.Mesh;
  };
  materials: {};
};
export function Plant2(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF(
    "/models/PlantBanjoFig/PlantBanjoFig.glb"
    // "/models/PlantBanjoFig/plantbanjofig-opt.glb"
  ) as GLTFResult;

  const [plantColorMap, plantNormalMap, plantRoughnessMap, plantMetalnessMap] =
    useLoader(
      THREE.TextureLoader,
      [
        "/models/PlantBanjoFig/PlantBanjoFig001_COL_2K_METALNESS.jpg",
        "/models/PlantBanjoFig/PlantBanjoFig001_NRM_2K_METALNESS.png",
        "/models/PlantBanjoFig/PlantBanjoFig001_ROUGHNESS_2K_METALNESS.jpg",
        "/models/PlantBanjoFig/PlantBanjoFig001_METALNESS_2K_METALNESS.png",
      ].map((src) => imageKitLoader({ src, quality: "80" }))
    ).map((texture) => {
      return texture;
    });
  const [vaseColorMap, vaseNormalMap, vaseRoughnessMap, vaseMetalnessMap] =
    useLoader(
      THREE.TextureLoader,
      [
        "/models/PlantBanjoFig/PlantBanjoFigVase001_COL_2K_METALNESS.jpg",
        "/models/PlantBanjoFig/PlantBanjoFigVase001_NRM_2K_METALNESS.png",
        "/models/PlantBanjoFig/PlantBanjoFigVase001_ROUGHNESS_2K_METALNESS.jpg",
        "/models/PlantBanjoFig/PlantBanjoFigVase001_METALNESS_2K_METALNESS.png",
      ].map((src) => imageKitLoader({ src, quality: "80" }))
    ).map((texture) => {
      texture.flipY = false;
      return texture;
    });

  return (
    <group {...props} position={[-0.1, -0.5, 0.84]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PlantBanjoFig001001.geometry}
        position={[-0.65, -0.284, -0.654]}
        rotation={[0, 0, Math.PI / 2]}
        // scale={0.544}
      >
        <meshStandardMaterial
          map={plantColorMap}
          normalMap={plantNormalMap}
          roughnessMap={plantRoughnessMap}
          metalnessMap={plantMetalnessMap}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PlantBanjoFigVase001001.geometry}
        position={[-0.602, -0.308, -0.716]}
        // scale={0.203}
      >
        <meshStandardMaterial
          map={vaseColorMap}
          normalMap={vaseNormalMap}
          roughnessMap={vaseRoughnessMap}
          metalnessMap={vaseMetalnessMap}
        />
      </mesh>
    </group>
  );
}
