/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Floor008: THREE.Mesh;
  };
  materials: {
    Floor: THREE.MeshStandardMaterial;
  };
};

export function Shelf(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/shelf.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor008.geometry}
        material={materials.Floor}
        scale={[0.583, 0.5, 0.018]}
      />
    </group>
  );
}
