/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Bowl: THREE.Mesh;
    Legs: THREE.Mesh;
    Top: THREE.Mesh;
  };
  materials: {
    Wood: THREE.MeshStandardMaterial;
    PaintedMetal: THREE.MeshStandardMaterial;
  };
};

export function SideTable(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/side-table.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bowl.geometry}
        material={materials.Wood}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Legs.geometry}
        material={materials.PaintedMetal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Top.geometry}
        material={materials.Wood}
      />
    </group>
  );
}

useGLTF.preload("/models/side-table.glb");
