/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    DECORATIVE_POT: THREE.Mesh;
    Leaves_0: THREE.Mesh;
    Leaves_1: THREE.Mesh;
    Leaves_10: THREE.Mesh;
    Leaves_11: THREE.Mesh;
    Leaves_12: THREE.Mesh;
    Leaves_13: THREE.Mesh;
    Leaves_14: THREE.Mesh;
    Leaves_15: THREE.Mesh;
    Leaves_16: THREE.Mesh;
    Leaves_17: THREE.Mesh;
    Leaves_18: THREE.Mesh;
    Leaves_19: THREE.Mesh;
    Leaves_2: THREE.Mesh;
    Leaves_3: THREE.Mesh;
    Leaves_4: THREE.Mesh;
    Leaves_5: THREE.Mesh;
    Leaves_6: THREE.Mesh;
    Leaves_7: THREE.Mesh;
    Leaves_8: THREE.Mesh;
    Leaves_9: THREE.Mesh;
    POT_SUPPORT: THREE.Mesh;
    Soil: THREE.Mesh;
    Terracotta_Pot: THREE.Mesh;
  };
  materials: {
    Pot: THREE.MeshStandardMaterial;
    SANSEVIERIA_LEAVES: THREE.MeshStandardMaterial;
    SUPPORT: THREE.MeshStandardMaterial;
    ["Soil.001"]: THREE.MeshPhysicalMaterial;
    ["Terracotta Pot"]: THREE.MeshStandardMaterial;
  };
};

export function SnakePlant(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/snake-plant.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.DECORATIVE_POT.geometry}
        material={materials.Pot}
        position={[0, 0, 0.05]}
      />
      <group position={[0, 0, 0.234]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaves_0.geometry}
          material={materials.SANSEVIERIA_LEAVES}
          position={[-0.009, 0.036, -0.001]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaves_1.geometry}
          material={materials.SANSEVIERIA_LEAVES}
          position={[0.032, 0.017, 0.001]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaves_10.geometry}
          material={materials.SANSEVIERIA_LEAVES}
          position={[-0.027, 0.043, -0.001]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaves_11.geometry}
          material={materials.SANSEVIERIA_LEAVES}
          position={[-0.006, 0.01, 0.002]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaves_12.geometry}
          material={materials.SANSEVIERIA_LEAVES}
          position={[0.027, -0.017, 0.001]}
          rotation={[0, 0.015, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaves_13.geometry}
          material={materials.SANSEVIERIA_LEAVES}
          position={[0.018, 0.017, 0.001]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaves_14.geometry}
          material={materials.SANSEVIERIA_LEAVES}
          position={[-0.048, 0.018, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaves_15.geometry}
          material={materials.SANSEVIERIA_LEAVES}
          position={[-0.021, -0.044, -0.001]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaves_16.geometry}
          material={materials.SANSEVIERIA_LEAVES}
          position={[-0.019, -0.012, 0.003]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaves_17.geometry}
          material={materials.SANSEVIERIA_LEAVES}
          position={[-0.028, 0.014, 0.001]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaves_18.geometry}
          material={materials.SANSEVIERIA_LEAVES}
          position={[0.016, -0.035, 0.001]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaves_19.geometry}
          material={materials.SANSEVIERIA_LEAVES}
          position={[-0.005, -0.027, 0.001]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaves_2.geometry}
          material={materials.SANSEVIERIA_LEAVES}
          position={[0.038, -0.013, -0.002]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaves_3.geometry}
          material={materials.SANSEVIERIA_LEAVES}
          position={[0.036, -0.042, 0.003]}
          rotation={[0.023, 0.003, 0.112]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaves_4.geometry}
          material={materials.SANSEVIERIA_LEAVES}
          position={[0.048, 0.006, -0.001]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaves_5.geometry}
          material={materials.SANSEVIERIA_LEAVES}
          position={[-0.062, -0.042, -0.003]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaves_6.geometry}
          material={materials.SANSEVIERIA_LEAVES}
          position={[0, -0.054, 0.002]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaves_7.geometry}
          material={materials.SANSEVIERIA_LEAVES}
          position={[-0.049, -0.009, -0.001]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaves_8.geometry}
          material={materials.SANSEVIERIA_LEAVES}
          position={[0.018, -0.008, 0.001]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Leaves_9.geometry}
          material={materials.SANSEVIERIA_LEAVES}
          position={[0.019, 0.033, 0]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.POT_SUPPORT.geometry}
        material={materials.SUPPORT}
        rotation={[0, 0, Math.PI / 4]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Soil.geometry}
        material={materials["Soil.001"]}
        position={[0, 0, 0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Terracotta_Pot.geometry}
        material={materials["Terracotta Pot"]}
        position={[0, 0, 0.061]}
      />
    </group>
  );
}

useGLTF.preload("/models/snake-plant.glb");
