/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    MainFloor: THREE.Mesh;
  };
  materials: {
    Floor: THREE.MeshStandardMaterial;
  };
};

export function Wall(props: JSX.IntrinsicElements["group"]) {
  return (
    <group {...props} dispose={null}>
      <mesh receiveShadow>
        {/* <meshStandardMaterial color="#FFC24D" /> */}
        <meshStandardMaterial color="#FFD468" />
        <planeGeometry args={[25, 20]} />
      </mesh>
      <mesh receiveShadow position={[0, -9.95, 0]}>
        <boxGeometry args={[10, 0.06, 0.02]} />
        <meshStandardMaterial color="#FFFFFF" />
      </mesh>
    </group>
  );
}
