/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    whale_Tessellation_fins: THREE.Mesh;
  };
  materials: {
    rattan: THREE.MeshPhysicalMaterial;
  };
};

export function WhaleWickerBasket(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/whale-wicker-basket-opt.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.whale_Tessellation_fins.geometry}
        material={materials.rattan}
        position={[0.017, -0.004, 0.236]}
        scale={0.345}
      />
    </group>
  );
}
